name=PATH DRC O3 Distribution
version=${project.version}
distro.distro-emr-configuration=${path-drc-distro.version}
distro.distro-emr-configuration.groupId=org.path.drc.omrs
distro.distro-emr-configuration.type=zip
content.path.drc-akram=${akram-content.version}
