name=PATH DRC O3 Distribution - Libiski
version=${project.version}
distro.distro-emr-configuration=${path-drc-distro.version}
distro.distro-emr-configuration.groupId=org.path.drc.omrs
distro.distro-emr-configuration.type=zip
content.path.drc-libikisi=${libikisi-content.version}
